name: Cypress Tests
on:
  push:
    branches:
      - main
env: 
  URL: $URL
  USERNAME: $USERNAME
  PASSWORD: $PASSWORD

jobs:
  cypress-run:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install
        run: npm install cypress --save-dev

      - name: ENV
        run: echo "URL=${{ env.URL }}" >> $GITHUB_ENV
             echo "LOGIN=${{ env.USERNAME }}" >> $GITHUB_ENV
             echo "PASSWORD=${{ env.PASSWORD }}" >> $GITHUB_ENV   

      - name: Run Cypress Tests
        working-directory: konstantinbv
        run:  npx cypress run --browser chrome
